### ISSUE TITLE
Name suggests it’s like length

### ISSUE THREAD

**Issue by ljharb** [RReverser/string-prototype-codepoints#4]
The name “codepoints” to me suggests it returns the number of code points in the string, like length does. Might there be another similar name that suggests it’s an iterator?

**Comment by mathiasbynens** [comment]
Why do you think it suggest such a thing? The name `codePoints` doesn’t have this connotation to me. If it were a getter (i.e. `string.codePoints;`) then I’d see the confusion, but it’s a method (i.e. `string.codePoints();`) which to me suggests it doesn’t just return a number.

**Comment by mathiasbynens** [comment]
Would you expect `array.values()` to return the number of values in the array?

**Comment by ljharb** [comment]
That’s a fair point; the getter definitely has more of that connotation to me than the method.

This isn’t that big a deal, i just wanted to bring it up :-)
