### ISSUE TITLE
what about chars?

### ISSUE THREAD

**Issue by ljharb** [RReverser/string-prototype-codepoints#5]
codePointAt → codePoints

charAt → chars?

I don’t have a use case and this might not be needed, but i wanted to ask about the potential inconsistency.

**Comment by michaelficarra** [comment]
Somebody might reasonably think that `chars` would return one-length strings, essentially `str.split('')`.

**Comment by mathiasbynens** [comment]
https://esdiscuss.org/topic/string-prototype-symbolat-improved-string-prototype-charat

**Comment by mathiasbynens** [comment]
comment removed as I got confused in yet another way

**Comment by ljharb** [comment]
@michaelficarra for consistency with `.codepoints()`, i would assume that it returns an iterable of one-length strings, yes - basically `str.split('')[Symbol.iterator]()`.

@mathiasbynens `.at` is a proposal I like (not sure what it's current status is tho), but that takes an index/position - is there a specific point in that esdiscuss thread that relates to this issue?

**Comment by michaelficarra** [comment]
@ljharb But `codePoints` doesn't iterate over strings, it iterates over code points (numbers) and positions. That's why I'm saying it would be different.

**Comment by ljharb** [comment]
@michaelficarra ah, fair point.
