### ISSUE TITLE
Integer versus string representation of code points

### ISSUE THREAD

**Issue by js-choi** [RReverser/string-prototype-codepoints#6]
https://github.com/RReverser/string-prototype-codepoints/issues/5#issuecomment-388481451 reminded me that I wanted to ask: Is there a particular reason why an integer representation for code points was chosen instead of a 1-or-2-UTF16-code-unit string representation? With the latter, 
`"\u0041\ud801\udc00\u0042".codePoints()` would then yield 
`"\u0041"` then 
`"\ud801\udc00"` then 
`"\u0042"`? 

I would personally find such a string representation to be more generally useful.  My parsers concatenate code points into new strings much more often than they perform integer arithmetic on them. But people’s usage here may vary, I suppose.

**Comment by michaelficarra** [comment]
We could just do both, as @mathiasbynens suggested: https://github.com/RReverser/string-prototype-codepoints/issues/1#issuecomment-348072474

**Comment by mathiasbynens** [comment]
Note that _if_ these string values are all you need, you can already get them by iterating over the string.

```js
for (const symbol of string) {
  console.log(symbol);
}
```

**Comment by js-choi** [comment]
@mathiasbynens: The default string iterator does not work for non-BMP code points (that is, code points beyond U+FFFF), such as the string in the example; it splits them into their surrogate pairs. `[..."\u0041\ud801\udc00\u0042"]`, aka `["A𐐀B"]`, results in an array with four strings each with one UTF-16 code unit (`["A", "\ud801", "\udc00", "B"]`), rather than three strings each with one Unicode code point (`["A", "𐐀", "B"]`). Use cases like these are why this repository’s proposal would be useful.

**Comment by ljharb** [comment]
This api would have to work the same as the default iterator imo to be called “codePoints”. It sounds like you want graphemes, which would be a separate thing?

**Comment by js-choi** [comment]
@ljharb: Could you clarify what you mean by “work the same as the default iterator”? The default iterator splits strings between their UTF-16 code units, not between their code points.

I don’t want graphemes in this case. As you probably already know, splitting strings by graphemes is a much more complicated problem than simply splitting by code points (or even by combining character sequence). Grapheme segmentation is language- and culture-dependent, its general rules as defined by [UAX 29](https://unicode.org/reports/tr29/) are really complex…and [`Intl.Segmenter`](https://github.com/tc39/proposal-intl-segmenter) will hopefully deal with graphemes eventually anyway.

My parsers often just want to handle Unicode text without splitting surrogate pairs; they need to consume each consecutive code point of the input string—rather than by UTF-16 code units or by combining character sequences or by graphemes.

Both `"\ud801\udc00"` and `10400` are reasonable representations of the same code point. Sometimes the former is more useful and sometimes the latter is more useful. But I usually find the former more useful.

**Comment by mathiasbynens** [comment]
@js-choi The default JS string iterator most definitely interates over code points rather than UCS-2/UTF-16 code units. Whichever engine behaves the way you described is violating the spec.

**Comment by mathiasbynens** [comment]
> The default iterator splits strings between their UTF-16 code units, not between their code points.

Where are you getting this? This is false.

**Comment by js-choi** [comment]
Ah, this is supremely embarrassing. You are of course correct; I had been recalling the default iterator’s behavior incorrectly. I’m not sure from where I got the false memory that it split between UTF-16 code units…I have been planning to port some parser code written in such languages to JavaScript for some time. I must have gotten wires crossed with some other programming languages that don’t split between code points. 

Heh, my sincere apologies; this issue is resolved. Thanks, everyone.
